name: Npm publish

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/npm.yaml'
      - 'package.json'
      - 'package-lock.json'
      - '.releaserc.json'
  workflow_dispatch:
jobs:
  build:
    name: Build to npm website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jules010209/discordjs-economie'
      - run: npm ci
      - run: npm test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
